server:
  port: 5000
spring:
  main:
    banner-mode: off
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initilaization-mode: always
    platform: postgres
    url: "jdbc:postgresql://localhost:5430/auth"
    username: "root"
    password: "root"
  security:
    user:
      username: "root"
      password: "root"
keycloak:
  auth-server-url: "http://localhost:8180/auth"
  realm: "micro-pki"
  resource: "auth-app"
  public-client: true
  principal-attribute: "preferred_username"
logging:
  level:
    org:
      springframework: ERROR
devtools:
  restart:
    enabled: true