server:
  port: 5000
spring:
  main:
    banner-mode: off
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    initilaization-mode: always
    platform: postgres
    url: "jdbc:postgresql://localhost:5430/auth"
    username: "root"
    password: "root"
  security:
    user:
      password: "foo"
logging:
  level:
    org:
      springframework: ERROR