version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq/
      - rabbit-log:/var/log/rabbitmq

  auth-db:
    container_name: pg_auth
    profiles: [ "db" ]
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    ports:
      - "5430:5432"
    volumes:
      - auth-pg:/var/lib/postgresql/data


  csr-db:
    container_name: pg_ca
    profiles: [ "db" ]
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: csr
    ports:
      - "5431:5432"
    volumes:
      - csr-pg:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:4.8.3.Final
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak
    ports:
      - "8180:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:10
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak
    volumes:
      - keycloak-pg:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    profiles: [ "db" ]
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  keycloak-pg:
  auth-pg:
  csr-pg:
  pgadmin:
  rabbit-data:
  rabbit-log:

